### ISSUE TITLE
Error: Package subpath './compiler.js' is not defined by "exports" in node_modules/svelte/package.json

### ISSUE THREAD

**Issue by MariusStuparu** [Samuel-Martineau/generator-svelte#7]
**Describe the bug**
Fresh deploy of the generator on MacOS Catalina and Node v14.3.0. Trying to run the `build` or `dev` scripts, `rollup` fails with this error:
```
[!] Error: Package subpath './compiler.js' is not defined by "exports" in node_modules/svelte/package.json
```

**Logs**
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './compiler.js' is not defined by "exports" in node_modules/svelte/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (node_modules/rollup-plugin-svelte/index.js:11:4)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
```
**Platform:**
 - OS: OSX Catalina
 - Generator version: 2.2.8
 - Node version: 14.3.0
 - NPM version: 5.3.0

**Comment by MariusStuparu** [comment]
There was a breaking change introduced in Svelte https://github.com/sveltejs/svelte/issues/5665

The fix is to update `rollup-plugin-svelte` to version 6.1.1

```
...
"rollup-plugin-svelte": "~6.1.1",
```

**Comment by Samuel-Martineau** [comment]
Thanks for your help! I’m fixing the template

**Comment by Samuel-Martineau** [comment]
It should be fixed right now [as all the tests pass](https://github.com/Samuel-Martineau/generator-svelte/actions/runs/358611571). You should upgrade to [`generator-svelte@2.2.9`](https://www.npmjs.com/package/generator-svelte/v/2.2.9).

Thanks for using `generator-svelte`!

**Comment by elimisteve** [comment]
FYI I didn't run into this with Node 10.x (10.23, specifically), but just upgraded to Node 12.x (12.20.0) then suddenly ran into this.

**Comment by Samuel-Martineau** [comment]
But does it work now with node 12?

**Comment by elimisteve** [comment]
Yes, the above fix worked (upgrading to 6.1.1), I'm just adding that I didn't get the "Package subpath" error at all when using Node 10.

**Comment by jeffRTC** [comment]
Goddamn. The whole ecosystem is rigged, rigged and should follow Windows Philosophy  of backwards compatibility. 

It's been a year since I wrote my app and it already broken.


WTF with X-Gen!!!!!

**Comment by sutin1234** [comment]
work for me 
https://github.com/Samuel-Martineau/generator-svelte/issues/7#issuecomment-725330501

**Comment by arb1ona** [comment]
> There was a breaking change introduced in Svelte [sveltejs/svelte#5665](https://github.com/sveltejs/svelte/issues/5665)
> 
> The fix is to update `rollup-plugin-svelte` to version 6.1.1
> 
> ```
> ...
> "rollup-plugin-svelte": "~6.1.1",
> ```
> 
> Couldn't create a fix branch on the repo, please update yourself.

Thank youu! It worked <3
